# Python for Machine Learning 3: Advanced Concepts

## Dictionaries

In [30]:
empty_dict = {}
fruit = {'apples':1, 'bananas': 2}

In [32]:
number_of_apples = fruit['apples']
print(number_of_apples)

1


In [33]:
for k, v in fruit.items():
    print(k, v)

apples 1
bananas 2


In [34]:
fruit['apples'] = 15

In [36]:
if 'apples' in fruit:
    print('We have', fruit['apples'], 'apples.')

We have 15 apples.


## Classes

In [51]:
class Apple():
    
    color = 'red'
    diameter = 4
    price = '0.0'
    
    def __init__(self):
        self.price = '1.99'

    def eat(self):
        self.diameter-=1
        if (self.diameter <=0):
            self.diameter = 0

In [52]:
a = Apple()
print(a.color)
print(a.price)
print(a.diameter)
a.eat()
print(a.diameter)

red
1.99
4
3


In [60]:
class FujiApple(Apple):
    
    def __init__(self):
        self.price = 2.99

In [61]:
b = FujiApple()
print(b.color)
print(b.price)
print(b.diameter)
b.eat()
print(b.diameter)

red
2.99
4
3


## Numpy

In [15]:
import numpy as np
a = np.zeros([3, 3, 3], dtype=np.float64)

In [19]:
print(a)
print(a.shape)
print(a.dtype)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(3, 3, 3)
float64


In [66]:
for x in range(10):
    print(np.random.random(), np.random.randint(10))
    
r = np.random.random(size=(3,3))
print(r)

0.9743675112286763 3
0.9975893201197789 8
0.12335598635171419 5
0.7138710343533687 7
0.10440628724580359 3
0.7247270501817518 8
0.13099563663758707 5
0.3438254639147412 3
0.6828805577230918 8
0.225069775651504 3
[[0.02196935 0.69960667 0.35406696]
 [0.50469692 0.93158479 0.76756089]
 [0.20620843 0.49396214 0.91447132]]


In [26]:
n=1
print(a[:,:,n])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Exercises (20')

1. Define a class `vehicle`, a class `car`, and a class `mercedes`. A Mercedes is a car which is a vehicle. Invent some placeholder attributes and methods (`drive()`, `price`, etc.), and build a Mercedes object.
2. `np.ones` creates NumPy arrays full of ones. Define a three-dimensional array (4x4x4) full of ones and set the value in the first row, second column, third z-plane to 0. Print the array to check if your implementation is correct.